sonar.projectKey=aurify-backend_Aurify-Analytics
sonar.organization=aurify-backend
sonar.projectName=Aurify-Analytics
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.test.inclusions=src/**/__tests__/**/*.test.ts